### ISSUE TITLE
Regarding running the docker-compose file

### ISSUE THREAD

**Issue by ahn1305** [galojix/roster-wizard#25]
When I ran the compose file, gregcowell/roster-wizard:latest, this particular image is not running. How to run this file properly

**Comment by gregcowell** [comment]
Please specify what error messages you are seeing.

**Comment by ahn1305** [comment]
sure, please give me few minutes

**Comment by ahn1305** [comment]
time="2024-04-17T10:27:38+05:30" level=warning msg="The \"USERID\" variable is not set. Defaulting to a blank string."
time="2024-04-17T10:27:38+05:30" level=warning msg="The \"GROUPID\" variable is not set. Defaulting to a blank string."
time="2024-04-17T10:27:38+05:30" level=warning msg="The \"USERID\" variable is not set. Defaulting to a blank string."
time="2024-04-17T10:27:38+05:30" level=warning msg="The \"GROUPID\" variable is not set. Defaulting to a blank string."
[+] Running 5/0
 ✔ Container roster-wizard-redis-1     Created                                                                                 0.0s 
 ✔ Container roster-wizard-rabbitmq-1  Created                                                                                 0.0s 
 ✔ Container roster-wizard-db-1        Created                                                                                 0.0s 
 ✔ Container roster-wizard-celery-1    Created                                                                                 0.0s 
 ✔ Container roster-wizard-web-1       Created                                                                                 0.0s 
Attaching to celery-1, db-1, rabbitmq-1, redis-1, web-1
db-1        | Error: Database is uninitialized and superuser password is not specified.
db-1        |        You must specify POSTGRES_PASSWORD to a non-empty value for the
db-1        |        superuser. For example, "-e POSTGRES_PASSWORD=password" on "docker run".
db-1        | 
db-1        |        You may also use "POSTGRES_HOST_AUTH_METHOD=trust" to allow all
db-1        |        connections without a password. This is *not* recommended.
db-1        |
db-1        |        See PostgreSQL documentation about "trust":
db-1        |        https://www.postgresql.org/docs/current/auth-trust.html
redis-1     | 1:C 17 Apr 2024 04:57:58.616 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis-1     | 1:C 17 Apr 2024 04:57:58.616 * Redis version=7.2.4, bits=64, commit=00000000, modified=0, pid=1, just started
redis-1     | 1:C 17 Apr 2024 04:57:58.616 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis-1     | 1:M 17 Apr 2024 04:57:58.639 * monotonic clock: POSIX clock_gettime
redis-1     | 1:M 17 Apr 2024 04:57:58.711 * Running mode=standalone, port=6379.
redis-1     | 1:M 17 Apr 2024 04:57:58.737 * Server initialized
redis-1     | 1:M 17 Apr 2024 04:57:58.751 * Loading RDB produced by version 7.2.4
redis-1     | 1:M 17 Apr 2024 04:57:58.751 * RDB age 113 seconds
redis-1     | 1:M 17 Apr 2024 04:57:58.751 * RDB memory usage when created 0.83 Mb
redis-1     | 1:M 17 Apr 2024 04:57:58.751 * Done loading RDB, keys loaded: 0, keys expired: 0.
redis-1     | 1:M 17 Apr 2024 04:57:58.751 * DB loaded from disk: 0.014 seconds
redis-1     | 1:M 17 Apr 2024 04:57:58.751 * Ready to accept connections tcp
db-1 exited with code 1
celery-1 exited with code 0
web-1 exited with code 0
rabbitmq-1  | 2024-04-17 04:58:15.495255+00:00 [notice] <0.44.0> Application syslog exited with reason: stopped
rabbitmq-1  | 2024-04-17 04:58:15.506917+00:00 [notice] <0.248.0> Logging: switching to configured handler(s); following messages may not be visible in this log output
rabbitmq-1  | 2024-04-17 04:58:15.508222+00:00 [notice] <0.248.0> Logging: configured log handlers are now ACTIVE
rabbitmq-1  | 2024-04-17 04:58:15.526769+00:00 [info] <0.248.0> ra: starting system quorum_queues
rabbitmq-1  | 2024-04-17 04:58:15.527007+00:00 [info] <0.248.0> starting Ra system: quorum_queues in directory: /var/lib/rabbitmq/mnesia/rabbit@rabbitmq1/quorum/rabbit@rabbitmq1
rabbitmq-1  | 2024-04-17 04:58:15.706829+00:00 [info] <0.262.0> ra system 'quorum_queues' running pre init for 0 registered servers
rabbitmq-1  | 2024-04-17 04:58:15.735637+00:00 [info] <0.263.0> ra: meta data store initialised for system quorum_queues. 0 record(s) recovered
rabbitmq-1  | 2024-04-17 04:58:15.776357+00:00 [notice] <0.268.0> WAL: ra_log_wal init, open tbls: ra_log_open_mem_tables, closed tbls: ra_log_closed_mem_tables
rabbitmq-1  | 2024-04-17 04:58:15.800486+00:00 [info] <0.248.0> ra: starting system coordination
rabbitmq-1  | 2024-04-17 04:58:15.800571+00:00 [info] <0.248.0> starting Ra system: coordination in directory: /var/lib/rabbitmq/mnesia/rabbit@rabbitmq1/coordination/rabbit@rabbitmq1
rabbitmq-1  | 2024-04-17 04:58:15.803999+00:00 [info] <0.275.0> ra system 'coordination' running pre init for 1 registered servers
rabbitmq-1  | 2024-04-17 04:58:15.830134+00:00 [info] <0.276.0> ra: meta data store initialised for system coordination. 1 record(s) recovered
rabbitmq-1  | 2024-04-17 04:58:15.830420+00:00 [notice] <0.281.0> WAL: ra_coordination_log_wal init, open tbls: ra_coordination_log_open_mem_tables, closed tbls: ra_coordination_log_closed_mem_tables
rabbitmq-1  | 2024-04-17 04:58:15.838620+00:00 [info] <0.248.0> ra: starting system coordination
rabbitmq-1  | 2024-04-17 04:58:15.838739+00:00 [info] <0.248.0> starting Ra system: coordination in directory: /var/lib/rabbitmq/mnesia/rabbit@rabbitmq1/coordination/rabbit@rabbitmq1
rabbitmq-1  | 2024-04-17 04:58:15.994937+00:00 [info] <0.248.0> Waiting for Khepri leader for 30000 ms, 9 retries left
rabbitmq-1  | 2024-04-17 04:58:16.031853+00:00 [info] <0.248.0> Khepri leader elected
rabbitmq-1  | 2024-04-17 04:58:16.627174+00:00 [notice] <0.285.0> RabbitMQ metadata store: candidate -> leader in term: 2 machine version: 0
rabbitmq-1  | 2024-04-17 04:58:19.715379+00:00 [info] <0.248.0> 
rabbitmq-1  | 2024-04-17 04:58:19.715379+00:00 [info] <0.248.0>  Starting RabbitMQ 3.13.1 on Erlang 26.2.4 [jit]
rabbitmq-1  | 2024-04-17 04:58:19.715379+00:00 [info] <0.248.0>  Copyright (c) 2007-2024 Broadcom Inc and/or its subsidiaries       
rabbitmq-1  | 2024-04-17 04:58:19.715379+00:00 [info] <0.248.0>  Licensed under the MPL 2.0. Website: https://rabbitmq.com
rabbitmq-1  |
rabbitmq-1  |   ##  ##      RabbitMQ 3.13.1
rabbitmq-1  |   ##  ##
rabbitmq-1  |   ##########  Copyright (c) 2007-2024 Broadcom Inc and/or its subsidiaries
rabbitmq-1  |   ######  ##
rabbitmq-1  |   ##########  Licensed under the MPL 2.0. Website: https://rabbitmq.com
rabbitmq-1  |
rabbitmq-1  |   Erlang:      26.2.4 [jit]
rabbitmq-1  |   TLS Library: OpenSSL - OpenSSL 3.1.5 30 Jan 2024
rabbitmq-1  |   Release series support status: supported
rabbitmq-1  |
rabbitmq-1  |   Doc guides:  https://www.rabbitmq.com/docs/documentation
rabbitmq-1  |   Support:     https://www.rabbitmq.com/docs/contact
rabbitmq-1  |   Tutorials:   https://www.rabbitmq.com/tutorials
rabbitmq-1  |   Monitoring:  https://www.rabbitmq.com/docs/monitoring
rabbitmq-1  |
rabbitmq-1  |   Logs: <stdout>
rabbitmq-1  |
rabbitmq-1  |   Config file(s): /etc/rabbitmq/conf.d/10-defaults.conf
rabbitmq-1  |                   /etc/rabbitmq/conf.d/20-management_agent.disable_metrics_collector.conf
rabbitmq-1  |
rabbitmq-1  |   Starting broker...2024-04-17 04:58:19.717785+00:00 [info] <0.248.0>
rabbitmq-1  | 2024-04-17 04:58:19.717785+00:00 [info] <0.248.0>  node           : rabbit@rabbitmq1
rabbitmq-1  | 2024-04-17 04:58:19.717785+00:00 [info] <0.248.0>  home dir       : /var/lib/rabbitmq
rabbitmq-1  | 2024-04-17 04:58:19.717785+00:00 [info] <0.248.0>  config file(s) : /etc/rabbitmq/conf.d/10-defaults.conf
rabbitmq-1  | 2024-04-17 04:58:19.717785+00:00 [info] <0.248.0>                 : /etc/rabbitmq/conf.d/20-management_agent.disable_metrics_collector.conf
rabbitmq-1  | 2024-04-17 04:58:19.717785+00:00 [info] <0.248.0>  cookie hash    : DCKGkxmUXfjSU+iAXF3exw==
rabbitmq-1  | 2024-04-17 04:58:19.717785+00:00 [info] <0.248.0>  log(s)         : <stdout>
rabbitmq-1  | 2024-04-17 04:58:19.717785+00:00 [info] <0.248.0>  data dir       : /var/lib/rabbitmq/mnesia/rabbit@rabbitmq1
rabbitmq-1  | 2024-04-17 04:58:20.079156+00:00 [info] <0.248.0> Running boot step pre_boot defined by app rabbit
rabbitmq-1  | 2024-04-17 04:58:20.079269+00:00 [info] <0.248.0> Running boot step rabbit_global_counters defined by app rabbit      
rabbitmq-1  | 2024-04-17 04:58:20.079843+00:00 [info] <0.248.0> Running boot step rabbit_osiris_metrics defined by app rabbit       
rabbitmq-1  | 2024-04-17 04:58:20.079972+00:00 [info] <0.248.0> Running boot step rabbit_core_metrics defined by app rabbit
rabbitmq-1  | 2024-04-17 04:58:20.085740+00:00 [info] <0.248.0> Running boot step rabbit_alarm defined by app rabbit
rabbitmq-1  | 2024-04-17 04:58:20.107831+00:00 [info] <0.408.0> Memory high watermark set to 1160 MiB (1217185382 bytes) of 2901 MiB (3042963456 bytes) total
rabbitmq-1  | 2024-04-17 04:58:20.119953+00:00 [info] <0.410.0> Enabling free disk space monitoring (disk free space: 979423477760, total memory: 3042963456)
rabbitmq-1  | 2024-04-17 04:58:20.120045+00:00 [info] <0.410.0> Disk free limit set to 50MB
rabbitmq-1  | 2024-04-17 04:58:20.122811+00:00 [info] <0.248.0> Running boot step code_server_cache defined by app rabbit
rabbitmq-1  | 2024-04-17 04:58:20.123055+00:00 [info] <0.248.0> Running boot step file_handle_cache defined by app rabbit
rabbitmq-1  | 2024-04-17 04:58:20.137387+00:00 [info] <0.413.0> Limiting to approx 1048479 file handles (943629 sockets)
rabbitmq-1  | 2024-04-17 04:58:20.137759+00:00 [info] <0.414.0> FHC read buffering: OFF
rabbitmq-1  | 2024-04-17 04:58:20.137819+00:00 [info] <0.414.0> FHC write buffering: ON
rabbitmq-1  | 2024-04-17 04:58:20.138721+00:00 [info] <0.248.0> Running boot step worker_pool defined by app rabbit
rabbitmq-1  | 2024-04-17 04:58:20.139135+00:00 [info] <0.341.0> Will use 12 processes for default worker pool
rabbitmq-1  | 2024-04-17 04:58:20.139663+00:00 [info] <0.341.0> Starting worker pool 'worker_pool' with 12 processes in it
rabbitmq-1  | 2024-04-17 04:58:20.140840+00:00 [info] <0.248.0> Running boot step database defined by app rabbit
rabbitmq-1  | 2024-04-17 04:58:20.141526+00:00 [info] <0.248.0> Peer discovery: configured backend: rabbit_peer_discovery_classic_config
rabbitmq-1  | 2024-04-17 04:58:20.145136+00:00 [info] <0.248.0> Waiting for Mnesia tables for 30000 ms, 9 retries left
rabbitmq-1  | 2024-04-17 04:58:20.155091+00:00 [info] <0.248.0> Successfully synced tables from a peer
rabbitmq-1  | 2024-04-17 04:58:20.167644+00:00 [info] <0.248.0> Waiting for Mnesia tables for 30000 ms, 9 retries left
rabbitmq-1  | 2024-04-17 04:58:20.167886+00:00 [info] <0.248.0> Successfully synced tables from a peer
rabbitmq-1  | 2024-04-17 04:58:20.168238+00:00 [info] <0.248.0> Running boot step tracking_metadata_store defined by app rabbit     
rabbitmq-1  | 2024-04-17 04:58:20.168340+00:00 [info] <0.436.0> Setting up a table for connection tracking on this node: tracked_connection
rabbitmq-1  | 2024-04-17 04:58:20.168400+00:00 [info] <0.436.0> Setting up a table for per-vhost connection counting on this node: tracked_connection_per_vhost
rabbitmq-1  | 2024-04-17 04:58:20.168940+00:00 [info] <0.436.0> Setting up a table for per-user connection counting on this node: tracked_connection_per_user
rabbitmq-1  | 2024-04-17 04:58:20.169030+00:00 [info] <0.436.0> Setting up a table for channel tracking on this node: tracked_channel
rabbitmq-1  | 2024-04-17 04:58:20.169494+00:00 [info] <0.436.0> Setting up a table for channel tracking on this node: tracked_channel_per_user
rabbitmq-1  | 2024-04-17 04:58:20.169639+00:00 [info] <0.248.0> Running boot step networking_metadata_store defined by app rabbit   
rabbitmq-1  | 2024-04-17 04:58:20.170003+00:00 [info] <0.248.0> Running boot step feature_flags defined by app rabbit
rabbitmq-1  | 2024-04-17 04:58:20.170232+00:00 [info] <0.248.0> Running boot step codec_correctness_check defined by app rabbit     
rabbitmq-1  | 2024-04-17 04:58:20.170285+00:00 [info] <0.248.0> Running boot step external_infrastructure defined by app rabbit     
rabbitmq-1  | 2024-04-17 04:58:20.170376+00:00 [info] <0.248.0> Running boot step rabbit_event defined by app rabbit
rabbitmq-1  | 2024-04-17 04:58:20.170601+00:00 [info] <0.248.0> Running boot step rabbit_registry defined by app rabbit
rabbitmq-1  | 2024-04-17 04:58:20.171064+00:00 [info] <0.248.0> Running boot step rabbit_auth_mechanism_amqplain defined by app rabbit
rabbitmq-1  | 2024-04-17 04:58:20.171170+00:00 [info] <0.248.0> Running boot step rabbit_auth_mechanism_cr_demo defined by app rabbit
rabbitmq-1  | 2024-04-17 04:58:20.171257+00:00 [info] <0.248.0> Running boot step rabbit_auth_mechanism_plain defined by app rabbit 
rabbitmq-1  | 2024-04-17 04:58:20.171328+00:00 [info] <0.248.0> Running boot step rabbit_exchange_type_direct defined by app rabbit 
rabbitmq-1  | 2024-04-17 04:58:20.171406+00:00 [info] <0.248.0> Running boot step rabbit_exchange_type_fanout defined by app rabbit 
rabbitmq-1  | 2024-04-17 04:58:20.171575+00:00 [info] <0.248.0> Running boot step rabbit_exchange_type_headers defined by app rabbit
rabbitmq-1  | 2024-04-17 04:58:20.171676+00:00 [info] <0.248.0> Running boot step rabbit_exchange_type_topic defined by app rabbit  
rabbitmq-1  | 2024-04-17 04:58:20.171750+00:00 [info] <0.248.0> Running boot step rabbit_mirror_queue_mode_all defined by app rabbit
rabbitmq-1  | 2024-04-17 04:58:20.172168+00:00 [info] <0.248.0> Running boot step rabbit_mirror_queue_mode_exactly defined by app rabbit
rabbitmq-1  | 2024-04-17 04:58:20.172236+00:00 [info] <0.248.0> Running boot step rabbit_mirror_queue_mode_nodes defined by app rabbit
rabbitmq-1  | 2024-04-17 04:58:20.172985+00:00 [info] <0.248.0> Running boot step rabbit_priority_queue defined by app rabbit       
rabbitmq-1  | 2024-04-17 04:58:20.173062+00:00 [info] <0.248.0> Priority queues enabled, real BQ is rabbit_variable_queue
rabbitmq-1  | 2024-04-17 04:58:20.173587+00:00 [info] <0.248.0> Running boot step rabbit_queue_location_client_local defined by app rabbit
rabbitmq-1  | 2024-04-17 04:58:20.173730+00:00 [info] <0.248.0> Running boot step rabbit_queue_location_min_masters defined by app rabbit
rabbitmq-1  | 2024-04-17 04:58:20.174390+00:00 [info] <0.248.0> Running boot step rabbit_queue_location_random defined by app rabbit
rabbitmq-1  | 2024-04-17 04:58:20.174585+00:00 [info] <0.248.0> Running boot step kernel_ready defined by app rabbit
rabbitmq-1  | 2024-04-17 04:58:20.174636+00:00 [info] <0.248.0> Running boot step rabbit_sysmon_minder defined by app rabbit        
rabbitmq-1  | 2024-04-17 04:58:20.175209+00:00 [info] <0.248.0> Running boot step rabbit_epmd_monitor defined by app rabbit
rabbitmq-1  | 2024-04-17 04:58:20.177389+00:00 [info] <0.444.0> epmd monitor knows us, inter-node communication (distribution) port: 25672
rabbitmq-1  | 2024-04-17 04:58:20.177670+00:00 [info] <0.248.0> Running boot step guid_generator defined by app rabbit
rabbitmq-1  | 2024-04-17 04:58:20.185764+00:00 [info] <0.248.0> Running boot step rabbit_node_monitor defined by app rabbit
rabbitmq-1  | 2024-04-17 04:58:20.186402+00:00 [info] <0.448.0> Starting rabbit_node_monitor (in ignore mode)
rabbitmq-1  | 2024-04-17 04:58:20.186576+00:00 [info] <0.248.0> Running boot step delegate_sup defined by app rabbit
rabbitmq-1  | 2024-04-17 04:58:20.187537+00:00 [info] <0.248.0> Running boot step rabbit_memory_monitor defined by app rabbit       
rabbitmq-1  | 2024-04-17 04:58:20.187909+00:00 [info] <0.248.0> Running boot step rabbit_fifo_dlx_sup defined by app rabbit
rabbitmq-1  | 2024-04-17 04:58:20.188358+00:00 [info] <0.248.0> Running boot step core_initialized defined by app rabbit
rabbitmq-1  | 2024-04-17 04:58:20.188643+00:00 [info] <0.248.0> Running boot step rabbit_channel_tracking_handler defined by app rabbit
rabbitmq-1  | 2024-04-17 04:58:20.189175+00:00 [info] <0.248.0> Running boot step rabbit_connection_tracking_handler defined by app rabbit
rabbitmq-1  | 2024-04-17 04:58:20.189525+00:00 [info] <0.248.0> Running boot step rabbit_definitions_hashing defined by app rabbit  
rabbitmq-1  | 2024-04-17 04:58:20.189757+00:00 [info] <0.248.0> Running boot step rabbit_exchange_parameters defined by app rabbit  
rabbitmq-1  | 2024-04-17 04:58:20.218096+00:00 [info] <0.248.0> Running boot step rabbit_mirror_queue_misc defined by app rabbit
rabbitmq-1  | 2024-04-17 04:58:20.219049+00:00 [info] <0.248.0> Running boot step rabbit_policies defined by app rabbit
rabbitmq-1  | 2024-04-17 04:58:20.220093+00:00 [info] <0.248.0> Running boot step rabbit_policy defined by app rabbit
rabbitmq-1  | 2024-04-17 04:58:20.220791+00:00 [info] <0.248.0> Running boot step rabbit_queue_location_validator defined by app rabbit
rabbitmq-1  | 2024-04-17 04:58:20.221245+00:00 [info] <0.248.0> Running boot step rabbit_quorum_memory_manager defined by app rabbit
rabbitmq-1  | 2024-04-17 04:58:20.221465+00:00 [info] <0.248.0> Running boot step rabbit_quorum_queue defined by app rabbit
rabbitmq-1  | 2024-04-17 04:58:20.221736+00:00 [info] <0.248.0> Running boot step rabbit_stream_coordinator defined by app rabbit   
rabbitmq-1  | 2024-04-17 04:58:20.222174+00:00 [info] <0.248.0> Running boot step rabbit_vhost_limit defined by app rabbit
rabbitmq-1  | 2024-04-17 04:58:20.222463+00:00 [info] <0.248.0> Running boot step rabbit_federation_parameters defined by app rabbitmq_federation
rabbitmq-1  | 2024-04-17 04:58:20.222985+00:00 [info] <0.248.0> Running boot step rabbit_federation_supervisor defined by app rabbitmq_federation
rabbitmq-1  | 2024-04-17 04:58:20.237390+00:00 [info] <0.248.0> Running boot step rabbit_federation_queue defined by app rabbitmq_federation
rabbitmq-1  | 2024-04-17 04:58:20.237702+00:00 [info] <0.248.0> Running boot step rabbit_federation_upstream_exchange defined by app rabbitmq_federation
rabbitmq-1  | 2024-04-17 04:58:20.237829+00:00 [info] <0.248.0> Running boot step rabbit_mgmt_db_handler defined by app rabbitmq_management_agent
rabbitmq-1  | 2024-04-17 04:58:20.237887+00:00 [info] <0.248.0> Management plugin: using rates mode 'basic'
rabbitmq-1  | 2024-04-17 04:58:20.238338+00:00 [info] <0.248.0> Running boot step recovery defined by app rabbit
rabbitmq-1  | 2024-04-17 04:58:20.277624+00:00 [info] <0.498.0> Making sure data directory '/var/lib/rabbitmq/mnesia/rabbit@rabbitmq1/msg_stores/vhosts/628WB79CIFDYO9LJI6DKMI09L' for vhost '/' exists
rabbitmq-1  | 2024-04-17 04:58:20.297653+00:00 [info] <0.498.0> Starting message stores for vhost '/'
rabbitmq-1  | 2024-04-17 04:58:20.298030+00:00 [info] <0.507.0> Message store "628WB79CIFDYO9LJI6DKMI09L/msg_store_transient": using rabbit_msg_store_ets_index to provide index
rabbitmq-1  | 2024-04-17 04:58:20.309652+00:00 [info] <0.498.0> Started message store of type transient for vhost '/'
rabbitmq-1  | 2024-04-17 04:58:20.309996+00:00 [info] <0.511.0> Message store "628WB79CIFDYO9LJI6DKMI09L/msg_store_persistent": using rabbit_msg_store_ets_index to provide index
rabbitmq-1  | 2024-04-17 04:58:20.314250+00:00 [info] <0.498.0> Started message store of type persistent for vhost '/'
rabbitmq-1  | 2024-04-17 04:58:20.314535+00:00 [info] <0.498.0> Recovering 0 queues of type rabbit_classic_queue took 35ms
rabbitmq-1  | 2024-04-17 04:58:20.314622+00:00 [info] <0.498.0> Recovering 0 queues of type rabbit_quorum_queue took 0ms
rabbitmq-1  | 2024-04-17 04:58:20.314725+00:00 [info] <0.498.0> Recovering 0 queues of type rabbit_stream_queue took 0ms
rabbitmq-1  | 2024-04-17 04:58:20.317835+00:00 [info] <0.248.0> Running boot step empty_db_check defined by app rabbit
rabbitmq-1  | 2024-04-17 04:58:20.317955+00:00 [info] <0.248.0> Will not seed default virtual host and user: have definitions to load...
rabbitmq-1  | 2024-04-17 04:58:20.317993+00:00 [info] <0.248.0> Running boot step rabbit_observer_cli defined by app rabbit
rabbitmq-1  | 2024-04-17 04:58:20.318277+00:00 [info] <0.248.0> Running boot step background_gc defined by app rabbit
rabbitmq-1  | 2024-04-17 04:58:20.318580+00:00 [info] <0.248.0> Running boot step routing_ready defined by app rabbit
rabbitmq-1  | 2024-04-17 04:58:20.318643+00:00 [info] <0.248.0> Running boot step pre_flight defined by app rabbit
rabbitmq-1  | 2024-04-17 04:58:20.318673+00:00 [info] <0.248.0> Running boot step notify_cluster defined by app rabbit
rabbitmq-1  | 2024-04-17 04:58:20.318720+00:00 [info] <0.248.0> Running boot step networking defined by app rabbit
rabbitmq-1  | 2024-04-17 04:58:20.318801+00:00 [info] <0.248.0> Running boot step rabbit_quorum_queue_periodic_membership_reconciliation defined by app rabbit
rabbitmq-1  | 2024-04-17 04:58:20.318996+00:00 [info] <0.248.0> Running boot step definition_import_worker_pool defined by app rabbit      
rabbitmq-1  | 2024-04-17 04:58:20.319069+00:00 [info] <0.341.0> Starting worker pool 'definition_import_pool' with 12 processes in it      
rabbitmq-1  | 2024-04-17 04:58:20.319792+00:00 [info] <0.248.0> Running boot step cluster_name defined by app rabbit
rabbitmq-1  | 2024-04-17 04:58:20.319886+00:00 [info] <0.248.0> Running boot step direct_client defined by app rabbit
rabbitmq-1  | 2024-04-17 04:58:20.320089+00:00 [info] <0.248.0> Running boot step rabbit_federation_exchange defined by app rabbitmq_federation
rabbitmq-1  | 2024-04-17 04:58:20.320585+00:00 [info] <0.557.0> Resetting node maintenance status
rabbitmq-1  | 2024-04-17 04:58:31.980325+00:00 [info] <0.595.0> Prometheus metrics: HTTP (non-TLS) listener started on port 15692
rabbitmq-1  | 2024-04-17 04:58:31.980557+00:00 [info] <0.557.0> Ready to start client connection listeners
rabbitmq-1  | 2024-04-17 04:58:31.983585+00:00 [info] <0.639.0> started TCP listener on [::]:5672
rabbitmq-1  |  completed with 4 plugins.
rabbitmq-1  | 2024-04-17 04:58:32.388007+00:00 [info] <0.557.0> Server startup complete; 4 plugins started.
rabbitmq-1  | 2024-04-17 04:58:32.388007+00:00 [info] <0.557.0>  * rabbitmq_prometheus
rabbitmq-1  | 2024-04-17 04:58:32.388007+00:00 [info] <0.557.0>  * rabbitmq_federation
rabbitmq-1  | 2024-04-17 04:58:32.388007+00:00 [info] <0.557.0>  * rabbitmq_management_agent
rabbitmq-1  | 2024-04-17 04:58:32.388007+00:00 [info] <0.557.0>  * rabbitmq_web_dispatch
rabbitmq-1  | 2024-04-17 04:58:32.516674+00:00 [info] <0.9.0> Time to start RabbitMQ: 31954 ms
![image](https://github.com/galojix/roster-wizard/assets/76400496/61e1642f-901d-4e3e-b1cb-20991af15f2a)

**Comment by gregcowell** [comment]
Looks like you may not have set the Postgres password as per the instructions: [here](https://www.galojix.com/case-studies/roster/roster-wizard-demonstration-evaluation-environment/)

**Comment by ahn1305** [comment]
is there any option to run this without a postgres database
