### ISSUE TITLE
Docker container

### ISSUE THREAD

**Issue by mterron** [galojix/roster-wizard#4]
Can you provide a dockerfile and docker-compose to stand up this project?

**Comment by gregcowell** [comment]
That is on my to-do list for when time permits. Also considering creating a Python package.

**Comment by gregcowell** [comment]
I've created development and production versions of dockerfile and docker-compose. The only thing missing from production is SSL/TLS certificate support.

**Comment by gregcowell** [comment]
Support for docker containers is complete.
